name: Backend CI

on: push

jobs:
    build:
        name: Build 🏗️
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1

            - run: |
                  cd ./backend/v1
                  bun install 
                  bun run build

    publish-docker-image:
        name: Publish Docker image 🚀
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and publish
              uses: docker/build-push-action@v5
              with:
                  context: ./backend/v1
                  push: true
                  tags: krystxf/metro-now-backend:latest
