name: Docs CI

on: push

jobs:
    docs-ci:
        name: Docs CI 📖
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                node: [20, 22]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}

            - uses: pnpm/action-setup@v3
              with:
                  version: 8

            - name: Lint
              continue-on-error: true
              run: |
                  cd ./docs
                  pnpm install 
                  pnpm run lint

            - name: Build
              run: |
                  cd ./docs
                  pnpm install 
                  pnpm run build
